### ISSUE TITLE
Cannot support redmine 3.2.X

### ISSUE THREAD

**Issue by archonwang** [previousnext/redmine_boards_watchers#10]
Thanks advanced. I used the plugin with branch 3.x
I make a migrate db but errors occured . as follows:

> Migrating redmine_boards_watchers (Extended watchers management and sticky priority levels add-on)...
> == 1 CreateMessageStickyPriority: migrating ===================================
> -- add_column(:messages, :sticky_priority, :integer, {:default=>0})
>    -> 0.0128s
> == 1 CreateMessageStickyPriority: migrated (0.0130s) ==========================
> 
> == 2 UpdateMessageStickyPriority: migrating ===================================
> rake aborted!
> An error has occurred, all later migrations canceled:
> 
> Couldn't find Message with 'id'=all/usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/activerecord-4.2.5.2/lib/active_record/relation/finder_methods.rb:324:in `raise_record_not_found_exception!'
> /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/activerecord-4.2.5.2/lib/active_record/relation/finder_methods.rb:444:in `find_one'
> /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/activerecord-4.2.5.2/lib/active_record/relation/finder_methods.rb:423:in `find_with_ids'
> /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/activerecord-4.2.5.2/lib/active_record/relation/finder_methods.rb:71:in `find'
> /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/activerecord-4.2.5.2/lib/active_record/querying.rb:3:in `find'
> /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/activerecord-4.2.5.2/lib/active_record/core.rb:130:in `find'
> /opt/redmine/plugins/redmine_boards_watchers/db/migrate/0002_update_message_sticky_priority.rb:3:in `up'
> /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/activerecord-4.2.5.2/lib/active_record/migration.rb:571:in `up'
> /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/activerecord-4.2.5.2/lib/active_record/migration.rb:611:in `exec_migration'
> /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/activerecord-4.2.5.2/lib/active_record/migration.rb:592:in `block (2 levels) in migrate'
> /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/activerecord-4.2.5.2/lib/active_record/migration.rb:591:in `block in migrate'
> /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/activerecord-4.2.5.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:292:in `with_connection'
> /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/activerecord-4.2.5.2/lib/active_record/migration.rb:590:in `migrate'
> /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/activerecord-4.2.5.2/lib/active_record/migration.rb:768:in `migrate'
> /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/activerecord-4.2.5.2/lib/active_record/migration.rb:998:in `block in execute_migration_in_transaction'
> /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/activerecord-4.2.5.2/lib/active_record/migration.rb:1046:in `ddl_transaction'
> /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/activerecord-4.2.5.2/lib/active_record/migration.rb:997:in `execute_migration_in_transaction'
> /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/activerecord-4.2.5.2/lib/active_record/migration.rb:959:in `block in migrate'
> /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/activerecord-4.2.5.2/lib/active_record/migration.rb:955:in `each'
> /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/activerecord-4.2.5.2/lib/active_record/migration.rb:955:in `migrate'
> /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/activerecord-4.2.5.2/lib/active_record/migration.rb:823:in `up'
> /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/activerecord-4.2.5.2/lib/active_record/migration.rb:801:in `migrate'
> /opt/redmine/lib/redmine/plugin.rb:481:in `migrate_plugin'
> /opt/redmine/lib/redmine/plugin.rb:453:in `migrate'
> /opt/redmine/lib/redmine/plugin.rb:467:in `block in migrate'
> /opt/redmine/lib/redmine/plugin.rb:466:in `each'
> /opt/redmine/lib/redmine/plugin.rb:466:in `migrate'
> /opt/redmine/lib/tasks/redmine.rake:127:in `block (3 levels) in <top (required)>'
> Tasks: TOP => redmine:plugins:migrate
> (See full trace by running task with --trace)

**Comment by archonwang** [comment]
Ok, I checked the database table named messages, and found there's no record in it. but I don't write ruby, anyone can fixed it? Thanks.
