### ISSUE TITLE
issue list right click to add watcher occured 500 error

### ISSUE THREAD

**Issue by archonwang** [previousnext/redmine_boards_watchers#11]
the error log as follows:

> Started GET "/boards_watchers/issues_watchers_bulk?back_url=%2Fprojects%2Futh_testteam%2Fissues&issues%5B%5D=21" for 192.168.60.239 at 2016-05-04 22:53:32 +0800
> Processing by BoardsWatchersController#issues_watchers_bulk as HTML
>   Parameters: {"back_url"=>"/projects/uth_testteam/issues", "issues"=>["21"]}
>   Current user: hui.wang (id=8)
> Completed 500 Internal Server Error in 8ms (ActiveRecord: 2.3ms)
> 
> NoMethodError (undefined method `find_all_by_id' for #<Class:0x00000003b861b0>):
>   plugins/redmine_boards_watchers/app/controllers/boards_watchers_controller.rb:105:in `setup_environment_issues'
>   lib/redmine/sudo_mode.rb:63:in `sudo_mode'
> 
>

**Comment by noneal** [comment]
Must replace line in app/controllers/boards_watchers_controller.rb:

      @issues = Issue.where(:id => (params[:issues]))
      #@issues=Issue.find_all_by_id(params[:issues])

find_all_by_id has been removed from redmine.
